### ISSUE TITLE
我也是T450S请教

### ISSUE THREAD

**Issue by m4ak** [findyy99/ThinkPad-T450S-Hackintosh-macOS-Big-Sur#1]
Big-Sur是直接升级上来的还是全新安装的？
还有我的是I5-5200U，ALC 292 可以直接用你这个EFI吗？

**Comment by findyy99** [comment]
@cchyswy 可以直升的话，你要把VirtualSMC换为FakeSMC，安装的时候要耐心等一下，安装之后，可以再将VirtualSMC换回来！可以的！有啥问题，可以提issue。

**Comment by m4ak** [comment]
我还没尝试，现在准备用你的EFI安装catalina，网卡使用1820A,安装后修改config.plist，改成DW1820A，不知道无线网卡和蓝牙会怎么样，能不能正常工作。

**Comment by findyy99** [comment]
不清楚1820A，1560都可以用
