### ISSUE TITLE
Help to use this repo

### ISSUE THREAD

**Issue by trgkyle** [findyy99/ThinkPad-T450S-Hackintosh-macOS-Big-Sur#4]
i really want to thank for your repo was supporting this device, i have no way to use with open-core to install mac-os in my thinkpad t450s, and haven't any experience install mac-os with hackintosh, please help me how can i use your BOOT file and OC file, i copied both of it to my EFI folder and set your BOOT UEFI config, it like be did work correctly, apple logo is crash, did i forget any step ? sorry about my Engish

**Comment by findyy99** [comment]
- I suppose you read this [guide](https://dortania.github.io/OpenCore-Install-Guide/installation/installation-process.html#double-checking-your-work) carefully. It also has many `General Troubleshooting`, you can learn from this.

- And if you have any other questions, please upload your log or error pic.

**Comment by trgkyle** [comment]
many thanks, currently i'm using macos in thinkpad t450s wow amazing, it seem works, the model wifi i'm using is DELL 1820A it works too

**Comment by findyy99** [comment]
No thanks! You are welcome!
