### ISSUE TITLE
DisplayPort on Dock not appears in "Displays" tab

### ISSUE THREAD

**Issue by matisiekpl** [findyy99/ThinkPad-T450S-Hackintosh-macOS-Big-Sur#7]
Hello.
I bought DisplayPort (not miniDisplayPort) to HDMI cable and I connected it to Dock. 
MacOS doesn't detected monitor so I entered BIOS.
I changed the BIOS Boot Display to "DisplayPort on Dock" and POST appeared so I am sure, that DisplayPort is working, but there is an issue in MacOS.
What should I do to fix this? I want to have two displays in "Displays" tab.
Thanks,
Matt

**Comment by findyy99** [comment]
Sorry, I don't have the monitor which was connected by DP port. I just tested the HDMI port on the Dock, I think you can try to change the `Hackintool/Patch/patch` and apply it to the `config.plist`. Remember backup your `config.plist`!

**Comment by matisiekpl** [comment]
Great! 
May I open PR with a working fix?
Thanks,
Matt

**Comment by findyy99** [comment]
@matisiekpl Yes! I am very happy if you can open a PR for this repo! Actually, I am preparing for a exam, after this I will update this repository!😬😬😬
